sudo: required

services:
  - docker

before_install:
  - docker build -t aankrose/docker-react .

script:
  - docker run -e CI=true aankrose/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-365854892832"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"